version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hiking_trail_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hiking_trail
      MYSQL_USER: hiking_user
      MYSQL_PASSWORD: hiking_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql_data: 